/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica.Cliente;

import Clases.Categorias;
import Clases.Clientes;
import Servicios.CategoriasService;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Pablo
 */
public class Menu extends javax.swing.JFrame {
    private Clientes cliente;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public Menu(Clientes cliente){
        this.cliente = cliente;
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnCatAlim = new javax.swing.JMenuItem();
        mnBebidas = new javax.swing.JMenuItem();
        mnJuguetes = new javax.swing.JMenuItem();
        mnElectronica = new javax.swing.JMenuItem();
        mnMascotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/CyberMonday_1.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("APROVECHA LAS OFERTAS");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("QUE TENEMOS PARA TI");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("2 de diciembre, TODO EL DIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jMenu2.setText("Inicio");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/house_5486876 (3).png"))); // NOI18N
        jMenuItem6.setText("Inicio");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mi cuenta");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/info_4014943.png"))); // NOI18N
        jMenuItem2.setText("Informacion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/clipboard_1917308.png"))); // NOI18N
        jMenuItem4.setText("Mis pedidos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/credit-card_5101661.png"))); // NOI18N
        jMenuItem3.setText("Metodos de pago");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/exit_7574347.png"))); // NOI18N
        jMenuItem5.setText("Cerrar Sesion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Categorias");

        mnCatAlim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/food_1029979.png"))); // NOI18N
        mnCatAlim.setText("Alimentos");
        mnCatAlim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCatAlimActionPerformed(evt);
            }
        });
        jMenu5.add(mnCatAlim);

        mnBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/juice_3165589.png"))); // NOI18N
        mnBebidas.setText("Bebidas");
        mnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBebidasActionPerformed(evt);
            }
        });
        jMenu5.add(mnBebidas);

        mnJuguetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/teddy-bear_3099403.png"))); // NOI18N
        mnJuguetes.setText("Juguetes");
        mnJuguetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJuguetesActionPerformed(evt);
            }
        });
        jMenu5.add(mnJuguetes);

        mnElectronica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/laptop_1081926.png"))); // NOI18N
        mnElectronica.setText("Electronica");
        mnElectronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnElectronicaActionPerformed(evt);
            }
        });
        jMenu5.add(mnElectronica);

        mnMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/dog_7403076.png"))); // NOI18N
        mnMascotas.setText("Mascotas");
        mnMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMascotasActionPerformed(evt);
            }
        });
        jMenu5.add(mnMascotas);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Carrito");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Cliente/Imagenes/shopping-cart_2478184.png"))); // NOI18N
        jMenuItem8.setText("Mi Carrito");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnJuguetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJuguetesActionPerformed
        // TODO add your handling code here:
        CategoriasService CS = new CategoriasService();
        String nombre = mnJuguetes.getText();
        Categorias categoria = CS.readCategoriaPorNombre(nombre);
        MostrarProductos pr = new MostrarProductos(categoria, cliente);
        pr.setVisible(true);
    }//GEN-LAST:event_mnJuguetesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        InformacionUsuario IU = new InformacionUsuario(this, true, cliente);
        IU.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            MetodoPago MP = new MetodoPago(this, true, cliente);
            MP.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        InicioClientes ic = new InicioClientes();
        ic.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnCatAlimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCatAlimActionPerformed
        // TODO add your handling code here:
        CategoriasService CS = new CategoriasService();
        String nombre = mnCatAlim.getText();
        Categorias categoria = CS.readCategoriaPorNombre(nombre);
        MostrarProductos pr = new MostrarProductos(categoria, cliente);
        pr.setVisible(true);
    }//GEN-LAST:event_mnCatAlimActionPerformed

    private void mnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBebidasActionPerformed
        // TODO add your handling code here:
        CategoriasService CS = new CategoriasService();
        String nombre = mnBebidas.getText();
        Categorias categoria = CS.readCategoriaPorNombre(nombre);
        MostrarProductos pr = new MostrarProductos(categoria, cliente);
        pr.setVisible(true);
    }//GEN-LAST:event_mnBebidasActionPerformed

    private void mnElectronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnElectronicaActionPerformed
        // TODO add your handling code here:
        CategoriasService CS = new CategoriasService();
        String nombre = "Electro";
        Categorias categoria = CS.readCategoriaPorNombre(nombre);
        MostrarProductos pr = new MostrarProductos(categoria, cliente);
        pr.setVisible(true);
    }//GEN-LAST:event_mnElectronicaActionPerformed

    private void mnMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMascotasActionPerformed
        // TODO add your handling code here:
        CategoriasService CS = new CategoriasService();
        String nombre = mnMascotas.getText();
        Categorias categoria = CS.readCategoriaPorNombre(nombre);
        MostrarProductos pr = new MostrarProductos(categoria, cliente);
        pr.setVisible(true);
    }//GEN-LAST:event_mnMascotasActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        MiCarrito MC = new MiCarrito(cliente);
        MC.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MisPedidos mp = new MisPedidos(cliente);
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnBebidas;
    private javax.swing.JMenuItem mnCatAlim;
    private javax.swing.JMenuItem mnElectronica;
    private javax.swing.JMenuItem mnJuguetes;
    private javax.swing.JMenuItem mnMascotas;
    // End of variables declaration//GEN-END:variables
}
