/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica.Cliente;

import Clases.Clientes;
import Clases.Compra;
import Clases.DetVentas;
import Clases.Domicilio;
import Clases.Envio;
import Clases.MetodoDePago;
import Clases.Productos;
import Clases.Proveedores;
import Servicios.ClientesService;
import Servicios.ComprasService;
import Servicios.DetVentasService;
import Servicios.DomicilioService;
import Servicios.EnvioService;
import Servicios.MetodosDePagoService;
import Servicios.ProductosService;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Pablo
 */
public class RealizarCompra extends javax.swing.JFrame {
    private Clientes cliente;
    DefaultTableModel modelo;
    /**
     * Creates new form Compra
     */
    public RealizarCompra() {
        initComponents();
    }
    
    public RealizarCompra(Clientes cliente) throws SQLException{
        this.cliente = cliente;
        initComponents();
        tblProductos.setEnabled(false);
        ListarCarrito();
        listarMetodosPago(cliente);
        lblTotal.setText("$" + cliente.getCarrito().calcularTotal());
        lblCantArticulos.setText("(" + cliente.getCarrito().calcularCantProd() + " ARTICULOS)");
        lblCalle.setText(cliente.getCalle() + " No. " + cliente.getNumero());
        lblCP.setText(cliente.getCodigoPostal());
        String ciudad = mostrarCiudad(cliente.getCoDomicilio());
        lblCoDomicilio.setText(ciudad);
    }
    
    public String mostrarCiudad(String codigo) throws SQLException{
        String ciudad = "";
        DomicilioService DS = new DomicilioService();
        Domicilio dom = DS.readDomicilioByCodigo(codigo);
        ciudad = dom.getCiudad() + ", " + dom.getEstado() + ", " + dom.getPais();
        return ciudad;
    }
    
    public void listarMetodosPago(Clientes cliente) throws SQLException{
        String idCte = cliente.getId();
        MetodosDePagoService MPS = new MetodosDePagoService();
        List<MetodoDePago> MetodosPago = MPS.readAllMp(idCte);
        for (MetodoDePago m : MetodosPago) {
            cbMetodosPago.addItem(m.getNumTarjeta());
        }
    }
    
    public void ListarCarrito(){
        ClientesService CS = new ClientesService();
        ProductosService PS = new ProductosService();
        ArrayList<Productos> productos = cliente.getCarrito().verProductos();
        modelo = (DefaultTableModel)tblProductos.getModel();
        Object ob[] = new Object[3];
        for (Productos p : productos) {
            ob[0] = p.getNombre();
            ob[1] = p.getDescripcion();
            ob[2] = p.getPrecio();
            modelo.addRow(ob);
        }
        tblProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantArticulos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        lblCP = new javax.swing.JLabel();
        lblCoDomicilio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMetodosPago = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnRealizarPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("REALIZAR COMPRA");

        lblCantArticulos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Dirección de envío");

        lblCalle.setText("jLabel3");

        lblCP.setText("jLabel3");

        lblCoDomicilio.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Metodo de pago");

        cbMetodosPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Productos");

        btnRealizarPedido.setBackground(new java.awt.Color(255, 255, 51));
        btnRealizarPedido.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRealizarPedido.setText("Realizar tu pedido y paga");
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Confirmacion de la compra");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblTotal.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(369, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbMetodosPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3)
                                    .addComponent(lblCoDomicilio)
                                    .addComponent(lblCP)
                                    .addComponent(lblCalle))
                                .addGap(18, 18, 18)
                                .addComponent(lblCantArticulos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotal)))
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCantArticulos))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(btnRealizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCP)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCoDomicilio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblTotal))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        // TODO add your handling code here:
        ComprasService CS = new ComprasService();
        DetVentasService DVS = new DetVentasService();
        EnvioService ES = new EnvioService();
        ArrayList<String> idsCompras = new ArrayList<>();
        ArrayList<String> idsEnvios = new ArrayList<>();
        ArrayList<Productos> listaProd = cliente.getCarrito().verProductos();
        try {
            idsCompras = CS.getAllComprasIDs();
            idsEnvios = ES.getAllEnviosIDs();
        } catch (SQLException ex) {
            Logger.getLogger(RealizarCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        DetVentas detVenta;
        Compra compra;
        Envio envio;
        Proveedores prov;
        String idProv;
        String idProd = "";
        int i = 0;
        int iEnv= 0;
        String idEnvio = "";
        String idCompra = "";
        String numProds = "";
        double total = 0;
        if (!cbMetodosPago.getSelectedItem().equals("---")) {
            try{
                LocalDate fechaActual = LocalDate.now();
                LocalDate fechaTresDiasDespues = fechaActual.plusDays(3);
                DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yy");
                String fecha = fechaActual.format(formatoFecha);
                String fechaEntrega = fechaTresDiasDespues.format(formatoFecha);
                i = idsCompras.size() + 1;
                iEnv = idsEnvios.size() + 1;
                idCompra = "C" + i;
                idEnvio = "E"+iEnv;
                numProds = String.valueOf(cliente.getCarrito().calcularCantProd());
                total = cliente.getCarrito().calcularTotal();
                compra = new Compra(idCompra, cliente.getId(), fecha, numProds, total);
                CS.createAndUpdateCompra(compra);
                for (Productos p : listaProd) {
                    idProd = p.getIdProd();
                    detVenta = new DetVentas(idCompra, idProd);
                    DVS.createAndUpdateDetVentas(detVenta);
                }
                cliente.getCompras().add(compra);
                idProv = listaProd.get(0).getIdProd();
                envio = new Envio(idEnvio, idProv, idCompra, fecha, fechaEntrega);
                ES.createAndUpadateEnvio(envio);
                JOptionPane.showMessageDialog(this, "Pedido realizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cliente.getCarrito().eliminarTodosProductos();
                this.setVisible(false);
            }catch(SQLException ex) {
                    Logger.getLogger(RealizarCompra.class.getName()).log(Level.SEVERE, "Error al realizar el pedido", ex); 
                    JOptionPane.showMessageDialog(this, "Error al procesar el pedido. Intente de nuevo más tarde.", "Error", JOptionPane.ERROR_MESSAGE);
                }
        }else{
            JOptionPane.showMessageDialog(null, "ELIJA UN METODO DE PAGO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JComboBox<String> cbMetodosPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCantArticulos;
    private javax.swing.JLabel lblCoDomicilio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
